### ISSUE TITLE
User returning error in slack message.

### ISSUE THREAD

**Issue by joejordanbrown** [ilhamrizqi/whmcs-hook-slack#2]
On line 22 of slack.php   `$adminuser = "ilham";` this should be the admin username we have on our own system so configuration needs to mention this.

Because otherwise we will have Error for the user section of the message.

> [ID: 22] Slack Test
> User: Error
> Department: Customer Support
> Testing slack

**Comment by ilhamrizqi** [comment]
OK, i'm going to patch the slack.php. Thank you for your contribution.

**Comment by Leykis** [comment]
Scratch that, was able to get it working. (edited)
